### ISSUE TITLE
opensand 6.1 Gateway got errors and crushed 

### ISSUE THREAD

**Issue by indieorganic** [CNES/opensand#6]
Just updated opensand to 6.1, using "openand-network setup -g 6 -s 2 -t 3" to setup network. Both  SAT2 and ST3 are initialized okay, but GW6 has errors and will be crushed after st3 logon. Here is the log of GW6:

[2022-12-29 11:06:03.276][ERROR][opensand][dvb.scheduling][ForwardSchedulingS2.cpp:scheduleEncapPackets():476] SF#478: The scheduling of a multicast frame failed
[2022-12-29 11:06:03.277][ERROR][opensand][dvb.scheduling][ForwardSchedulingS2.cpp:scheduleEncapPackets():480] SF#478: The Tal_Id corresponding to the terminal using the lower modcod can not be retrieved
[2022-12-29 11:06:03.277][ERROR][opensand][dvb.channel.receive][SpotDownward.cpp:handleFwdFrameTimer():1216] failed to schedule encapsulation packets stored in DVB FIFO for category Standard
[2022-12-29 11:06:03.277][ERROR][opensand][dvb.downward.rt][RtChannelBase.cpp:executeThread():568] failed to process event fwd_timer
[2022-12-29 11:06:10.958][ERROR][opensand][dvb.scheduling][ForwardSchedulingS2.cpp:scheduleEncapPackets():476] SF#1220: The scheduling of a multicast frame failed
[2022-12-29 11:06:10.958][ERROR][opensand][dvb.scheduling][ForwardSchedulingS2.cpp:scheduleEncapPackets():480] SF#1220: The Tal_Id corresponding to the terminal using the lower modcod can not be retrieved
[2022-12-29 11:06:10.958][ERROR][opensand][dvb.channel.receive][SpotDownward.cpp:handleFwdFrameTimer():1216] failed to schedule encapsulation packets stored in DVB FIFO for category Standard
[2022-12-29 11:06:10.958][ERROR][opensand][dvb.downward.rt][RtChannelBase.cpp:executeThread():568] failed to process event fwd_timer
[2022-12-29 11:06:13.892][EVENT][opensand][spot_6.dvb.logon_request]Logon request received from ST3 on spot 6
[2022-12-29 11:06:13.892][EVENT][opensand][spot_6.gw.dvb.logon_response]Logon response send to ST3 on spot 6
terminate called without an active exception
Traceback (most recent call last):
  File "/usr/bin/opensand-network", line 406, in <module>
    main(**args)
  File "/usr/bin/opensand-network", line 172, in launch
    subprocess.run(command, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ip', 'netns', 'exec', 'gw6', 'sudo', '-E', '-u', 'harry', 'opensand', '-v', '-i', './infrastructure.xml', '-t', './topology.xml', '-p', './profile.xml']' died with <Signals.SIGSEGV: 11>

**Comment by weiziping123-beep** [comment]
Hi, could you please let me know if you've resolved this issue? I'm running into the exact same error: "The scheduling of a multicast frame failed"
